lab05/app5/app5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

lab05/app5/myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"
urlpatterns = [
    path("",views.index, name= "index"),
    path("add/",views.add, name = "add"),
]

lab05/app5/myapp/models.py
from django.db import models

# Create your models here.

lab05/app5/myapp/views.py
from django import forms
from django.shortcuts import render

from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.

class askForInput(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="password")
    

def index(request):
    if "myapp" not in request.session:
        request.session["myapp"] = []
        
        
        
    return render(request,"myapp/index.html",{
        "myapp": request.session["myapp"]
        })
    
    
def add(request):
    
    if request.method == "POST":
        form = askForInput(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            
           
            
            request.session["myapp"] += [username]
            request.session["myapp"] += [password]
            
            return HttpResponseRedirect(reverse("myapp:index"))
        
        else:
            return render(request, "myapp/add.html",{
                "form":form
            })
        
    return render(request,"myapp/add.html",
        {"form": askForInput()
    })

lab05/app5/myapp/templates/myapp/add.html
{% extends "myapp/layout.html" %}

{% block body %}
    <h1>Register:</h1>

    <form action="{% url 'myapp:add' %}" method="post" >
        {% csrf_token %}
        <div id ="db">
            {{ form.as_p }}
            <input type = "submit">
        </div>
    </form>
    
    <div id= "center">
       
        <a href="{% url 'myapp:index' %}">
            <input type="button" value="Veiw List" id ="button" >
        </a>
    </div> 
{% endblock %}


 

lab05/app5/myapp/templates/myapp/index.html
{% extends "myapp/layout.html" %}

{% block body %}




    <div id = "db">
        <h1 id="header">people list </h2>
            {% for x in myapp %}
                <span id ="item">{{x}}</span>
            {% endfor %}
    </div>       

    <div id= "center">
       
        <a href="{% url 'myapp:add' %}">
            <input type="button" value="Register" id ="button" >
        </a>
    </div>  
       
    
{% endblock %}

lab05/app5/myapp/templates/myapp/layout.html
{% load static %}
<html lang="en">

<head>
    <title>app</title>
    <link rel= "stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    
    {% block body %}
    {% endblock %}
</body>
</html>